name:                ingestair
version:             0.1.0.0
github:              "ClairBerlin/ingestair"
license:             BSD3
author:              "Ulrich Schuster"
maintainer:          "ulrich.schuster@koing.de"
copyright:           "2021 Ulrich Schuster"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ingestair#readme>

dependencies:
- base
- rio

ghc-options:
# Recommended options from https://github.com/commercialhaskell/rio#monads
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fwarn-tabs
# For stan to work. See https://github.com/kowainik/stan#usage-instructions
- -fwrite-ide-info
- -hiedir=.hie

executables:
  ingestair-exe:
    main:                Main.hs
    source-dirs:         ingestair
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ingestair-persistence
    - ingestair-interactor
    - ingestair-usecases
    - envy
    - servant
    - servant-server
    - warp
    - bytestring
    - wai-extra

tests:
  ingestair-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ingestair-interactor
