name:                ingestair-api
version:             0.1.0.0
github:              "githubuser/ingestair-api"
license:             BSD3
author:              "Ulrich Schuster"
maintainer:          "ulrich.schuster@koing.de"
copyright:           "2021 Ulrich Schuster"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/servant-rio#readme>

dependencies:
- base
- rio

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fwarn-tabs

library:
  source-dirs:
  - src
  exposed-modules:
  - Ingestair.Api.Api
  dependencies:
  - ingestair-domain
  - aeson
  - servant
  - servant-server
  - scientific
  - uuid
  # - servant-swagger
  # - servant-swagger-ui
  # - swagger2

tests:
  ingestair-domain-test:
    main:                Test.hs
    source-dirs:
    # - test
    - src
    dependencies:
    - ingestair-domain
    - time
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-discover
    - QuickCheck
    - quickcheck-instances
    - quickcheck-text
    - checkers

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N