
@startuml dependencies

[Envy]#LightGrey
[Wai/Warp]#LightGrey
[Servant]#LightGrey
[JSON:API]#LightGrey
[Opaleye]#LightGrey

[Application]
[WebGateway]
[PersistenceGateway]
[Usecases]
[Domain]

[Application] --> [Envy]
[Application] --> [Wai/Warp]
[Application] --> [PersistenceGateway]
[Application] --> [WebGateway]
[Application] --> [Usecases]
[WebGateway] --> [Domain]
[WebGateway] --> [Usecases]
[WebGateway] --> [Servant]
[WebGateway] --> [JSON:API]
[WebGateway] --> [Wai/Warp]
[PersistenceGateway] --> [Usecases]
[PersistenceGateway] --> [Domain]
[PersistenceGateway] --> [Opaleye]
[Usecases] --> [Domain]

@enduml